name: Deploy Dash Redirect Page to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dash pandas numpy plotly

    - name: Build HTML page
      run: |
        mkdir -p public
        echo '<!DOCTYPE html>
        <html>
        <head>
          <title>Redirigiendo al Dashboard de Ventas</title>
          <meta http-equiv="refresh" content="0; url=http://localhost:8050/" />
          <style>
            body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
            .spinner { margin: 40px auto; width: 50px; height: 50px; border: 5px solid #f3f3f3; border-top: 5px solid #3498db; border-radius: 50%; animation: spin 1s linear infinite; }
            @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
          </style>
        </head>
        <body>
          <h1>Redirigiendo al Dashboard de Ventas...</h1>
          <div class="spinner"></div>
          <p>Si no eres redirigido automáticamente, <a href="http://localhost:8050/">haz clic aquí</a>.</p>
        </body>
        </html>' > public/index.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
